### ISSUE TITLE
Creating local client connection fails

### ISSUE THREAD

**Issue by uxes** [alandoherty/node-lxd#13]
Creating connection to [local unix connection](https://github.com/alandoherty/node-lxd/blob/master/docs/client.md#connection) fails. version `node-lxd@0.2.9`

```
/var/www/nodejs/node_modules/node-lxd/src/classes/Client.js:567
      if (!err && authenticate.cert) {
                              ^

TypeError: Cannot read property 'cert' of undefined
    at /var/www/nodejs/node_modules/node-lxd/src/classes/Client.js:567:31
    at /var/www/nodejs/node_modules/node-lxd/src/classes/Client.js:358:7
    at Request._callback (/var/www/nodejs/node_modules/node-lxd/src/classes/Client.js:504:13)
    at Request.self.callback (/var/www/nodejs/node_modules/request/request.js:199:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/var/www/nodejs/node_modules/request/request.js:1036:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/var/www/nodejs/node_modules/request/request.js:963:12)
```

**Comment by alandoherty** [comment]
Could you create a pull request from your forked version?

**Comment by alandoherty** [comment]
Fixed
